window.hoMenuItems = [
  { id: "m1", category: "mittag", name: "M1. Rau Curry", description: "Saisongemuse, rote Kokosmilch-Currysosse, Reis als Beilage.", price: 11 },
  { id: "m2", category: "mittag", name: "M2. Dau Phu Curry", description: "Gebratener Tofu, Saisongemuse, rote Kokosmilch-Currysosse, Reis.", price: 11 },
  { id: "m3", category: "mittag", name: "M3. Dau Xao La Que", description: "Gebratener Tofu, Thai-Basilikum, Saisongemuse, Reis.", price: 11 },
  { id: "m4", category: "mittag", name: "M4. Ga Curry", description: "Zartes Huhnerbrustfilet, rote Kokosmilch-Currysosse, Saisongemuse, Reis.", price: 11 },
  { id: "m5", category: "mittag", name: "M5. Ga Nuong Sot Xoai", description: "Gegrilltes Huhnerbrustfilet, Kokosmilch-Mangosauce, Saisongemuse, Reis.", price: 11 },
  { id: "m6", category: "mittag", name: "M6. Ga Xao Hat Dieu", description: "Zartes Huhnerbrustfilet, Cashewnusse, Saisongemuse, Reis.", price: 11 },
  { id: "m7", category: "mittag", name: "M7. Bo Xao Hat Dieu", description: "Gebratenes Rindfleisch, Cashewnusse, Saisongemuse, Reis.", price: 12 },
  { id: "m8", category: "mittag", name: "M8. Vit Curry", description: "Knusprige Ente, rote Kokosmilch-Currysosse, Saisongemuse, Reis.", price: 12 },
  { id: "m9", category: "mittag", name: "M9. Vit Sot Lac", description: "Knusprige Ente, Kokosmilch-Erdnusssosse, Saisongemuse, Reis.", price: 12 },
  { id: "m10", category: "mittag", name: "M10. Vit Hat Dieu", description: "Knusprige Ente, Cashewnusse, Saisongemuse, Reis.", price: 12 },
  { id: "m11", category: "mittag", name: "M11. Tom Curry", description: "Riesengarnelen, rote Kokosmilch-Currysosse, Saisongemuse, Reis.", price: 12 },
  { id: "m12", category: "mittag", name: "M12. Bun Dau Phu", description: "Lauwarme Reisnudeln, Tofu, Salatblattern, frische Krauter und hausgemachtes Dressing.", price: 11 },
  { id: "m13", category: "mittag", name: "M13. My Xao Ga", description: "Gebratene Weizennudeln, zartes Huhnerbrustfilet, Ei, Saisongemuse und Rostzwiebeln.", price: 11 },
  { id: "m14", category: "mittag", name: "M14. Pho Bo", description: "Reisbandnudeln, kraftige Bruhe, Rindfleisch, Fruhlingszwiebeln und frische Krauter.", price: 12 },

  { id: "v1", category: "vorspeisen", name: "V1. Sup Miso", description: "Miso-Suppe mit Seidentofustuckchen, Seetang, Dashi und Sojabohnenpaste.", price: 4 },
  { id: "v2a", category: "vorspeisen", name: "V2. Sup Chua Ngot mit Huhnerbrustfilet", description: "Suss-Sauer-Suppe mit Pilzen, Zitronengras und frischen Krautern.", price: 6 },
  { id: "v2b", category: "vorspeisen", name: "V2. Sup Chua Ngot mit Garnelen", description: "Suss-Sauer-Suppe mit Pilzen, Zitronengras und frischen Krautern.", price: 7 },
  { id: "v3a", category: "vorspeisen", name: "V3. Sup Nuoc Dua mit Huhnerbrustfilet", description: "Kokosmilchsuppe mit Pilzen, Zitronengras und frischen Krautern.", price: 6 },
  { id: "v3b", category: "vorspeisen", name: "V3. Sup Nuoc Dua mit Garnelen", description: "Kokosmilchsuppe mit Pilzen, Zitronengras und frischen Krautern.", price: 7 },
  { id: "v4", category: "vorspeisen", name: "V4. Seafood Popcorns", description: "Gebackene Garnelen und Sepia im knusprigen Teigmantel, serviert mit Chili-Mayonnaise-Sosse.", price: 7 },
  { id: "v5", category: "vorspeisen", name: "V5. Edamame", description: "Junge gekochte Sojabohnen am Zweig, verfeinert mit Salz oder Shichimi Nanami.", price: 5 },
  { id: "v6", category: "vorspeisen", name: "V6. Krabbenchips", description: "Knusprige Krabbenchips.", price: 3 },
  { id: "v7", category: "vorspeisen", name: "V7. Cha Gio Chay", description: "Vegane Fruhlingsrollchen mit Gemuse, 6 Stuck.", price: 4 },
  { id: "v8", category: "vorspeisen", name: "V8. Cha Gio Viet Nam", description: "Vietnamesische Fruhlingsrollen mit Schweinehackfleisch, Garnelen, Ei, Glasnudeln und Gemuse, dazu hausgemachte Sosse, 2 Stuck.", price: 6 },
  { id: "v9", category: "vorspeisen", name: "V9. Hoanh Thanh Chien", description: "Knusprig gebackene Dreiecke mit Garnelen-Huhnerfleisch-Fullung, 4 Stuck.", price: 6 },
  { id: "v10", category: "vorspeisen", name: "V10. Ga Xien Sate", description: "Gegrillte Huhnerfleischspiesschen, dazu Erdnusssosse, 3 Stuck.", price: 6 },
  { id: "v11", category: "vorspeisen", name: "V11. Ha Cao Tom", description: "Gedampfte Dumplings mit Garnelenfullung.", price: 7 },
  { id: "v12a", category: "vorspeisen", name: "V12. Gyoza mit Gemusefullung", description: "Gedampfte und dann gegrillte Teigtaschen, 5 Stuck.", price: 6 },
  { id: "v12b", category: "vorspeisen", name: "V12. Gyoza mit Huhnerfleischfullung", description: "Gedampfte und dann gegrillte Teigtaschen, 5 Stuck.", price: 7 },
  { id: "v13", category: "vorspeisen", name: "V13. Ebi Tempura (2 Stk.)", description: "Knusprige Riesengarnelen im Tempuramantel, dazu scharfe japanische Mayonnaise als Dip.", price: 8 },
  { id: "v14a", category: "vorspeisen", name: "V14. Goi Cuon mit Tofu (2 Stk.)", description: "Sommerrollen mit Reisnudeln, Eierstich, Salatblattern und frischen Krautern, dazu Hoisin-Kokosmilch-Dip.", price: 5 },
  { id: "v14b", category: "vorspeisen", name: "V14. Goi Cuon mit Huhnerbrustfilet (2 Stk.)", description: "Sommerrollen mit Reisnudeln, Eierstich, Salatblattern und frischen Krautern, dazu Hoisin-Kokosmilch-Dip.", price: 6 },
  { id: "v14c", category: "vorspeisen", name: "V14. Goi Cuon mit Garnelen (2 Stk.)", description: "Sommerrollen mit Reisnudeln, Eierstich, Salatblattern und frischen Krautern, dazu Hoisin-Kokosmilch-Dip.", price: 7 },
  { id: "v15", category: "vorspeisen", name: "V15. Salat Du Du Tom", description: "Gruner Papayasalat mit Riesengarnelen, frischen Krautern, Chili und hausgemachtem Dressing.", price: 9 },
  { id: "v16", category: "vorspeisen", name: "V16. Salat Xoai Vit", description: "Mango-Ente-Salat mit frischen Krautern und hausgemachtem Dressing.", price: 9 },
  { id: "v17", category: "vorspeisen", name: "V17. Goma Wakame", description: "Wurziger Seealgensalat mit Sesam.", price: 5 },
  { id: "v18a", category: "vorspeisen", name: "V18. Bunter Salat mit Huhnerbrustfilet", description: "Avocado, grune Erbsen, Gurke, Mango, Salatblatter, frische Krauter und Huhnerbrustfilet.", price: 12 },
  { id: "v18b", category: "vorspeisen", name: "V18. Bunter Salat mit Garnelen", description: "Avocado, grune Erbsen, Gurke, Mango, Salatblatter, frische Krauter und Garnelen.", price: 12 },
  { id: "v18c", category: "vorspeisen", name: "V18. Bunter Salat mit Lachs", description: "Avocado, grune Erbsen, Gurke, Mango, Salatblatter, frische Krauter und Lachs.", price: 12 },
  { id: "v18d", category: "vorspeisen", name: "V18. Bunter Salat mit Thunfisch", description: "Avocado, grune Erbsen, Gurke, Mango, Salatblatter, frische Krauter und Thunfisch.", price: 12 },
  { id: "v19", category: "vorspeisen", name: "V19. Lachs Tatar", description: "Wurzig abgeschmeckter Lachs mit Avocado, Fruhlingszwiebeln und Chilisosse.", price: 8 },
  { id: "v20", category: "vorspeisen", name: "V20. Thunfisch Tatar", description: "Wurzig abgeschmeckter Thunfisch mit Avocado, Fruhlingszwiebeln und Chilisosse.", price: 9 },

  { id: "r1", category: "reisgerichte", name: "1. Rau Curry", description: "Gebratenes Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 13 },
  { id: "r2", category: "reisgerichte", name: "2. Dau Phu Curry", description: "Gebratener Tofu und Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 14 },
  { id: "r3", category: "reisgerichte", name: "3. Dau Phu Sa Ot", description: "Gebratener Tofu mit Zitronengras, Chili und Saisongemuse, mit Reis.", price: 14 },
  { id: "r4", category: "reisgerichte", name: "4. Dau Phu Xao Hat Dieu", description: "Gebratener Tofu mit Cashewnussen und Saisongemuse, mit Reis.", price: 14 },
  { id: "r20", category: "reisgerichte", name: "20. Ga Curry", description: "Zartes Huhnerbrustfilet und Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 15 },
  { id: "r21", category: "reisgerichte", name: "21. Ga Sot Xoai", description: "Gegrilltes Huhnerbrustfilet mit Saisongemuse in Kokosmilch-Mangosauce, mit Reis.", price: 15 },
  { id: "r22", category: "reisgerichte", name: "22. Ga Sot Lac", description: "Gegrilltes Huhnerbrustfilet und Saisongemuse in Kokosmilch-Erdnusssosse, mit Reis.", price: 15 },
  { id: "r23", category: "reisgerichte", name: "23. Ga Xao Hat Dieu", description: "Zartes Huhnerbrustfilet mit Cashewnussen und Saisongemuse, mit Reis.", price: 15 },
  { id: "r24", category: "reisgerichte", name: "24. Ga Xao Sa Ot", description: "Zartes Huhnerbrustfilet mit Zitronengras, Chili und Saisongemuse, mit Reis.", price: 15 },
  { id: "r25", category: "reisgerichte", name: "25. Ga Pikant", description: "Gegrilltes Huhnerbrustfilet und Saisongemuse in pikanter Sosse, mit Reis.", price: 15 },
  { id: "r30", category: "reisgerichte", name: "30. Bo Curry", description: "Gebratenes Rindfleisch mit Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 16 },
  { id: "r31", category: "reisgerichte", name: "31. Bo Xao Sa Ot", description: "Gebratenes Rindfleisch mit Zitronengras, Chili und Saisongemuse, mit Reis.", price: 16 },
  { id: "r32", category: "reisgerichte", name: "32. Bo Xao Hat Dieu", description: "Gebratenes Rindfleisch mit Cashewnussen und Saisongemuse, mit Reis.", price: 16 },
  { id: "r33", category: "reisgerichte", name: "33. Bo Xao Tieu Xanh", description: "Gebratenes Rindfleisch mit frischem Grunpfeffer und Saisongemuse, mit Reis.", price: 16 },
  { id: "r34", category: "reisgerichte", name: "34. Dschingis Khan", description: "Paprika und Zwiebeln in wurziger BBQ-Sosse mit zartem Rindfleisch aus der Gusseisenpfanne.", price: 16 },
  { id: "r35", category: "reisgerichte", name: "35. Bo Teriyaki", description: "Im Wok geschwenkte Rindfleischwurfel mit Paprika und Zwiebeln.", price: 16 },
  { id: "r40", category: "reisgerichte", name: "40. Vit Curry", description: "Knusprige Ente mit Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 18 },
  { id: "r41", category: "reisgerichte", name: "41. Vit Sot Xoai", description: "Knusprige Ente mit Saisongemuse in Kokosmilch-Mangosauce, mit Reis.", price: 18 },
  { id: "r42", category: "reisgerichte", name: "42. Vit Sot Lac", description: "Knusprige Ente mit Saisongemuse in Kokosmilch-Erdnusssosse, mit Reis.", price: 18 },
  { id: "r43", category: "reisgerichte", name: "43. Vit Hat Dieu", description: "Knusprige Ente und Saisongemuse mit Cashewnussen, mit Reis.", price: 18 },
  { id: "r44", category: "reisgerichte", name: "44. Vit Pikant", description: "Knusprige Ente mit Saisongemuse in pikanter Sosse, mit Reis.", price: 18 },
  { id: "r50", category: "reisgerichte", name: "50. Ca Curry", description: "Gegrilltes Lachsfilet mit Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 19 },
  { id: "r51", category: "reisgerichte", name: "51. Ca La Que", description: "Gegrilltes Lachsfilet mit Thai-Basilikum und Saisongemuse, mit Reis.", price: 19 },
  { id: "r52", category: "reisgerichte", name: "52. Ca Pikant", description: "Gegrilltes Lachsfilet mit Saisongemuse in pikanter Sosse, mit Reis.", price: 19 },
  { id: "r53", category: "reisgerichte", name: "53. Salmon Teriyaki", description: "Lachsfilet, gewurfelt und kurz angebraten in Teriyaki-Sosse mit gerostetem Sesam-Topping.", price: 19 },
  { id: "r54", category: "reisgerichte", name: "54. Tuna Teriyaki", description: "Thunfischfilet, gewurfelt und kurz angebraten in Teriyaki-Sosse mit gerostetem Sesam-Topping.", price: 19 },
  { id: "r60", category: "reisgerichte", name: "60. Tom Curry", description: "Gebratene Riesengarnelen mit Saisongemuse in roter Kokosmilch-Currysosse, mit Reis.", price: 19 },
  { id: "r61", category: "reisgerichte", name: "61. Tom La Que", description: "Gebratene Riesengarnelen mit Thai-Basilikum und Saisongemuse, mit Reis.", price: 19 },
  { id: "r62", category: "reisgerichte", name: "62. Tom Xao Tieu Xanh", description: "Gebratene Riesengarnelen mit frischem Grunpfeffer und Saisongemuse, mit Reis.", price: 19 },

  { id: "n70", category: "nudeln", name: "70. Bun Dau Phu", description: "Lauwarme Reisnudeln mit gebratenem Tofu, Salatblattern, frischen Krautern, Erdnussen und hausgemachtem Dressing.", price: 14 },
  { id: "n71", category: "nudeln", name: "71. Bun Nem", description: "Lauwarme Reisnudeln mit vietnamesischen Fruhlingsrollen, Salatblattern, frischen Krautern, Erdnussen und hausgemachtem Dressing. Auch vegetarisch moglich.", price: 14 },
  { id: "n72", category: "nudeln", name: "72. Bun Bo Xao", description: "Lauwarme Reisnudeln mit gebratenem Rindfleisch, Zwiebeln, Salatblattern, frischen Krautern und hausgemachtem Dressing.", price: 16 },
  { id: "n73", category: "nudeln", name: "73. Bun Ga Xao", description: "Lauwarme Reisnudeln mit zartem Huhnerbrustfilet, Salatblattern, frischen Krautern, Erdnussen und hausgemachtem Dressing.", price: 15 },
  { id: "n74", category: "nudeln", name: "74. Bun Vit", description: "Lauwarme Reisnudeln mit knuspriger Ente, Salatblattern, frischen Krautern, Erdnussen und hausgemachtem Dressing.", price: 18 },
  { id: "n75a", category: "nudeln", name: "75. Pho mit Tofu", description: "Traditionelle vietnamesische Reisbandnudelsuppe mit Fruhlingszwiebeln, frischen Krautern und kraftiger Bruhe.", price: 14 },
  { id: "n75b", category: "nudeln", name: "75. Pho mit Huhnerbrustfilet", description: "Traditionelle vietnamesische Reisbandnudelsuppe mit Fruhlingszwiebeln, frischen Krautern und kraftiger Bruhe.", price: 15 },
  { id: "n75c", category: "nudeln", name: "75. Pho mit Rindfleisch (Entrecote)", description: "Traditionelle vietnamesische Reisbandnudelsuppe mit Fruhlingszwiebeln, frischen Krautern und kraftiger Bruhe.", price: 16 },

  { id: "sm1", category: "sushi-basic", name: "S1. Kappa Maki (8 Stk.)", description: "Gurke, Sesam und Frischkase.", price: 4.5 },
  { id: "sm2", category: "sushi-basic", name: "S2. Avocado Maki (8 Stk.)", description: "Avocado, Sesam und Frischkase.", price: 4.5 },
  { id: "sm3", category: "sushi-basic", name: "S3. Shinko Maki (8 Stk.)", description: "Eingelegter Rettich und Sesam.", price: 4.5 },
  { id: "sm4", category: "sushi-basic", name: "S4. Spicy Sake Maki (8 Stk.)", description: "Lachs und Schnittlauch.", price: 5.9 },
  { id: "sm5", category: "sushi-basic", name: "S5. Asupara Maki (8 Stk.)", description: "Gruner Spargel.", price: 4.5 },
  { id: "sm6", category: "sushi-basic", name: "S6. Sake Maki (8 Stk.)", description: "Lachs.", price: 5.6 },
  { id: "sm7", category: "sushi-basic", name: "S7. Tekka Maki (8 Stk.)", description: "Thunfisch.", price: 5.9 },
  { id: "sm8", category: "sushi-basic", name: "S8. Ebi Maki (8 Stk.)", description: "Garnelen.", price: 5.9 },
  { id: "sn1", category: "sushi-basic", name: "N1. Sake Nigiri (2 Stk.)", description: "Lachs.", price: 4.9 },
  { id: "sn2", category: "sushi-basic", name: "N2. Maguro Nigiri (2 Stk.)", description: "Thunfisch.", price: 5.5 },
  { id: "sn3", category: "sushi-basic", name: "N3. Ebi Nigiri (2 Stk.)", description: "Garnelen.", price: 5.5 },
  { id: "sn4", category: "sushi-basic", name: "N4. Hotate Nigiri (2 Stk.)", description: "Feuerjakobsmuschel.", price: 6.9 },
  { id: "sn5", category: "sushi-basic", name: "N5. Avocado Nigiri (2 Stk.)", description: "Avocado.", price: 4.5 },
  { id: "sn6", category: "sushi-basic", name: "N6. Ikura Nigiri (2 Stk.)", description: "Lachskaviar.", price: 7.5 },
  { id: "sn7", category: "sushi-basic", name: "N7. Unagi Nigiri (2 Stk.)", description: "Susswasseraal, Gurke und Sesam.", price: 5.9 },
  { id: "sn8", category: "sushi-basic", name: "N8. Inari Nigiri (2 Stk.)", description: "Frittierter Tofu.", price: 4.9 },
  { id: "sn9a", category: "sushi-basic", name: "N9. Kazumi Special Nigiri mit Mango (2 Stk.)", description: "Flambierter Lachs mit Mango.", price: 7.2 },
  { id: "sn9b", category: "sushi-basic", name: "N9. Kazumi Special Nigiri mit Avocado (2 Stk.)", description: "Flambierter Lachs mit Avocado.", price: 7.2 },
  { id: "sn10a", category: "sushi-basic", name: "N10. Sakao Special Nigiri mit Mango (2 Stk.)", description: "Flambierter Thunfisch mit Mango.", price: 7.5 },
  { id: "sn10b", category: "sushi-basic", name: "N10. Sakao Special Nigiri mit Avocado (2 Stk.)", description: "Flambierter Thunfisch mit Avocado.", price: 7.5 },
  { id: "ss9", category: "sushi-basic", name: "S9. Sake Sashimi", description: "Sashimi mit Lachs.", price: 18.9 },
  { id: "ss10", category: "sushi-basic", name: "S10. Maguro Sashimi", description: "Sashimi mit Thunfisch.", price: 19.9 },
  { id: "ss11", category: "sushi-basic", name: "S11. Maguro to Sake Sashimi", description: "Sashimi mit Thunfisch und Lachs.", price: 19.9 },

  { id: "sx1", category: "sushi-rolls", name: "M1. Hiro Sushi Mix", description: "4 Nigiri und 1 Inside Out.", price: 17.9 },
  { id: "sx2", category: "sushi-rolls", name: "M2. Tokyo Sushi Mix", description: "4 Nigiri, 1 Inside Out und Sashimi.", price: 24.9 },
  { id: "sx3", category: "sushi-rolls", name: "M3. Sakura Sushi Mix", description: "Maki Avo, Maki Tekka und Inside Out.", price: 17.8 },
  { id: "sx4", category: "sushi-rolls", name: "M4. Kyoto Sushi Mix", description: "Sushi fur 2 Personen, vegan oder vegetarisch.", price: 45.9 },
  { id: "sx5", category: "sushi-rolls", name: "M5. Shibuya Sushi Mix", description: "4 Nigiri und Rettich Maki.", price: 17.9 },
  { id: "sx6", category: "sushi-rolls", name: "M6. Sushi fur 2", description: "Sushi-Special vom Koch zusammengestellt. Bitte Unvertraglichkeiten vorab mitteilen.", price: 49.9 },
  { id: "sx7", category: "sushi-rolls", name: "M7. Sushi fur 3", description: "Sushi-Special vom Koch zusammengestellt. Bitte Unvertraglichkeiten vorab mitteilen.", price: 75 },
  { id: "sx8", category: "sushi-rolls", name: "M8. Sushi fur 4", description: "Sushi-Special vom Koch zusammengestellt. Bitte Unvertraglichkeiten vorab mitteilen.", price: 99.9 },
  { id: "st1", category: "sushi-rolls", name: "T1. Emi Tempura Roll (8 Stk.)", description: "Panierte Rolle mit Frischkase, Sesam, Teriyakisauce, Lachs und Avocado.", price: 15.9 },
  { id: "st2", category: "sushi-rolls", name: "T2. Shizuka Tempura Roll (8 Stk.)", description: "Panierte Rolle mit Frischkase, Sesam, Teriyakisauce, Jakobsmuscheln, Avocado und Schnittlauch.", price: 17.9 },
  { id: "st3", category: "sushi-rolls", name: "T3. Naomi Tempura Roll (8 Stk.)", description: "Panierte Rolle mit Frischkase, Sesam, Teriyakisauce, mariniertem Thunfisch, Gurke und Schnittlauch.", price: 16.9 },
  { id: "st4", category: "sushi-rolls", name: "T4. Natsumi Tempura Roll (8 Stk.)", description: "Panierte Rolle mit Frischkase, Sesam, Teriyakisauce, Surimi und Avocado.", price: 14.9 },
  { id: "st5", category: "sushi-rolls", name: "T5. Noriko Tempura Roll vegetarisch (6 Stk.)", description: "Gebackene Rolle mit Rettich, Gurke und Avocado.", price: 13.9 },
  { id: "st6", category: "sushi-rolls", name: "T6. Kazuki Tempura Roll vegetarisch (6 Stk.)", description: "Gebackene Rolle mit Mango und Avocado.", price: 13.9 },
  { id: "st7", category: "sushi-rolls", name: "T7. Mikio Tempura Roll vegetarisch (6 Stk.)", description: "Gebackene Rolle mit Spargel, Rucola und Gurke.", price: 13.9 },
  { id: "su1", category: "sushi-rolls", name: "U1. Tango Tuna Roe Inside Out (8 Stk.)", description: "Gekochter Thunfisch, Schnittlauch, Gurke, Frischkase und Sesam.", price: 11.9 },
  { id: "su2", category: "sushi-rolls", name: "U2. Knusprige Ente Inside Out (8 Stk.)", description: "Knusprige Ente mit Gurke, Frischkase und Rucola.", price: 12.9 },
  { id: "su3", category: "sushi-rolls", name: "U3. Creamy Alaska Inside Out (8 Stk.)", description: "Lachs, Avocado und Tobiko.", price: 10.9 },
  { id: "su4", category: "sushi-rolls", name: "U4. Exotic Salmon Inside Out (8 Stk.)", description: "Lachs, Mango und Tobiko.", price: 10.9 },
  { id: "su5", category: "sushi-rolls", name: "U5. Sake Kawa Inside Out (8 Stk.)", description: "Gegrillte Lachshaut und Gurke.", price: 10.9 },
  { id: "su6", category: "sushi-rolls", name: "U6. Pirikara Inside Out (8 Stk.)", description: "Thunfisch, pikante Gurke und Schnittlauch.", price: 12.9 },
  { id: "su7", category: "sushi-rolls", name: "U7. Oregon Inside Out (8 Stk.)", description: "Garnele, Rucola und Tobiko.", price: 10.9 },
  { id: "su8", category: "sushi-rolls", name: "U8. California Inside Out (8 Stk.)", description: "Surimi, Avocado und Tobiko.", price: 9.9 },
  { id: "su9", category: "sushi-rolls", name: "U9. Shiso Inside Out (8 Stk.)", description: "Aal, Avocado, Gurke und Tobiko.", price: 12.9 },
  { id: "su10", category: "sushi-rolls", name: "U10. Junko Inside Out (8 Stk.)", description: "Thunfisch und Avocado.", price: 10.9 },
  { id: "su11", category: "sushi-rolls", name: "U11. Yukari Inside Out (8 Stk.)", description: "Lachs, Tempura und Rucola.", price: 10.9 },
  { id: "su12", category: "sushi-rolls", name: "U12. Aiko Inside Out (8 Stk.)", description: "Knuspriges Hahnchen und Mango.", price: 10.9 },
  { id: "su13", category: "sushi-rolls", name: "U13. Ebi Tempura Inside Out (8 Stk.)", description: "Frittierte Garnele und Sesam.", price: 10.9 },
  { id: "su14", category: "sushi-rolls", name: "U14. Crunchy Chicken Inside Out (8 Stk.)", description: "Knuspriges Hahnchen und Rucola.", price: 10.9 },
  { id: "sv1", category: "sushi-rolls", name: "V1. Nevada Veggie Inside Out (8 Stk.)", description: "Gurke und Avocado.", price: 7.9 },
  { id: "sv2", category: "sushi-rolls", name: "V2. Texas Veggie Inside Out (8 Stk.)", description: "Gurke und Rucola.", price: 8.9 },
  { id: "sv3", category: "sushi-rolls", name: "V3. Kaori Veggie Inside Out (8 Stk.)", description: "Avocado und Tempura.", price: 8.9 },
  { id: "sv4", category: "sushi-rolls", name: "V4. Juicy Lee Veggie Inside Out (8 Stk.)", description: "Mango.", price: 7.9 },
  { id: "sv5", category: "sushi-rolls", name: "V5. Creamy Spargel Veggie Inside Out (8 Stk.)", description: "Rucola und Spargel Tempura.", price: 8.9 },
  { id: "sv6", category: "sushi-rolls", name: "V6. Sayuri Veggie Special Roll (6 Stk.)", description: "Spargel Tempura, Rucola und frittierter Tofu on Top.", price: 11.9 },
  { id: "sv7", category: "sushi-rolls", name: "V7. Kyo Veggie Special Roll (6 Stk.)", description: "Avocado Tempura und Mango on Top.", price: 11.9 },
  { id: "sv8", category: "sushi-rolls", name: "V8. Avocado Veggie Special Roll (6 Stk.)", description: "Gurke, Spargel und Avocado on Top.", price: 11.9 },
  { id: "sh20", category: "sushi-rolls", name: "U20. Yoko Special Homemade (8 Stk.)", description: "Gegrillte Lachshaut, Gurke, Avocado und Lachs on Top.", price: 13.9 },
  { id: "sh21", category: "sushi-rolls", name: "U21. Hitomi Special Homemade (8 Stk.)", description: "Surimi Tempura, Gurke und flambierter Lachs on Top.", price: 13.9 },
  { id: "sh22", category: "sushi-rolls", name: "U22. Tomoko Special Homemade (8 Stk.)", description: "Gemuse Tempura, Mayonnaise und Lachs on Top.", price: 13.9 },
  { id: "sh23", category: "sushi-rolls", name: "U23. Modori Special Homemade (8 Stk.)", description: "Avocado Tempura und flambierter Lachs on Top.", price: 13.9 },
  { id: "sh24", category: "sushi-rolls", name: "U24. Hiro 1 Special Homemade (8 Stk.)", description: "Lachs, Mango und flambierter Lachs on Top.", price: 13.9 },
  { id: "sh25", category: "sushi-rolls", name: "U25. Ochi Special Homemade (8 Stk.)", description: "Gemuse Tempura und flambierter Thunfisch on Top.", price: 13.9 },
  { id: "sh26", category: "sushi-rolls", name: "U26. Daiki Special Homemade (8 Stk.)", description: "Garnele Tempura, Rucola und flambierter Lachs on Top.", price: 14.9 },
  { id: "sh27", category: "sushi-rolls", name: "U27. Momo Special Homemade (8 Stk.)", description: "Spargel Tempura, Rucola und flambierter Lachs on Top.", price: 13.9 },
  { id: "sh28", category: "sushi-rolls", name: "U28. Ebisu Special Homemade (8 Stk.)", description: "Garnelen Tempura, Gurke und Aal on Top.", price: 15.9 },
  { id: "sh29", category: "sushi-rolls", name: "U29. Hiro 2 Special Homemade (8 Stk.)", description: "Garnelen Tempura, Gurke und Avocado on Top.", price: 13.9 },
  { id: "sb1", category: "sushi-rolls", name: "B1. Kyo 2 Big Roll (6 Stk.)", description: "Panierte Rollen mit grunen Reisflocken, Frischkase, Sesam, Lachs, Avocado, Spargel und Schnittlauch.", price: 10.9 },
  { id: "sb2", category: "sushi-rolls", name: "B2. Aiko Big Roll (6 Stk.)", description: "Marinierter Thunfisch, Spargel, Gurke und Schnittlauch.", price: 10.9 },
  { id: "sb3", category: "sushi-rolls", name: "B3. Sayuri Big Roll (6 Stk.)", description: "Garnelen, Avocado, Gurke und Schnittlauch.", price: 10.9 },
  { id: "sf1", category: "sushi-rolls", name: "F1. Naomi Futomaki (6 Stk.)", description: "Surimi Tempura, Gurke, Avocado und Frischkase.", price: 10.9 },
  { id: "sf2", category: "sushi-rolls", name: "F2. Natsumi Futomaki (6 Stk.)", description: "Garnele, Avocado, Rucola, Gurke und Frischkase.", price: 11.9 },
  { id: "sf3", category: "sushi-rolls", name: "F3. Kokoro Futomaki (6 Stk.)", description: "Lachs, Tobiko, frittierte Avocado, Gurke und Frischkase.", price: 11.9 },
  { id: "sc1", category: "sushi-rolls", name: "C1. Vegetarisch Chirashi Sushi Bowl", description: "Sushi-Reis, Wakame, Kimchi, Gemuse, hausgemachte Sosse und verschiedenes Gemuse.", price: 10.9 },
  { id: "sc2", category: "sushi-rolls", name: "C2. Sake Chirashi Sushi Bowl", description: "Sushi-Reis, Wakame, Kimchi, Gemuse, hausgemachte Sosse und marinierter roher Lachs.", price: 14.9 },
  { id: "sc3", category: "sushi-rolls", name: "C3. Tekka Chirashi Sushi Bowl", description: "Sushi-Reis, Wakame, Kimchi, Gemuse, hausgemachte Sosse und marinierter Thunfisch.", price: 16.9 },
  { id: "sc4", category: "sushi-rolls", name: "C4. Hiro Bowl", description: "Chirashi Sushi Bowl mit Huhnchen in Teriyaki-Sosse.", price: 12.9 },
  { id: "sc5", category: "sushi-rolls", name: "C5. Unagi Chirashi Sushi Bowl", description: "Chirashi Sushi Bowl mit gegrilltem Aal.", price: 15.9 },
  { id: "sc6", category: "sushi-rolls", name: "C6. Breaded Salmon Chirashi Sushi Bowl", description: "Chirashi Sushi Bowl mit paniertem Lachs.", price: 14.9 },
  { id: "sig1", category: "sushi-rolls", name: "Signature 1", description: "Inside: Avocado, Rettich, Tobiko, Reis, Frischkase. Outside: Lachs.", price: 13 },
  { id: "sig2", category: "sushi-rolls", name: "Signature 2", description: "Inside: Avocado, Rettich, Tobiko, Thunfisch und gekochte Garnelen. Outside: Reispapier.", price: 16 },
  { id: "sig3", category: "sushi-rolls", name: "Signature 3", description: "Inside: Rettich, Lachs, Sesam, gekochte Garnelen und Gurke. Outside: Reispapier mit Sesam.", price: 16 },
  { id: "sig4", category: "sushi-rolls", name: "Signature 4", description: "Inside: Gurke, Lachs, Thunfisch und Rettich. Outside: Noriblatter und Reispapier mit Sesam.", price: 14 },
  { id: "sig5", category: "sushi-rolls", name: "Signature 5", description: "Lachs, Avocado, Rettich, gekochte Garnelen, Tobiko, Chilifaden und Zitronenscheiben.", price: 14 },
  { id: "sig6", category: "sushi-rolls", name: "Signature 6", description: "Nigiri mit Avocado, Lachs, Reis, Noriblatter, Frischkase und Tobiko.", price: 11 },
  { id: "sig7", category: "sushi-rolls", name: "Signature 7", description: "Mosaic Cubes mit Reis, Lachs, Rettich und Gurke.", price: 10 },
  { id: "sig8", category: "sushi-rolls", name: "Signature 8", description: "Rolls mit Reis, Lachs, Rettich und Schnittlauch.", price: 11 },
  { id: "sushi_person_1", category: "sushi-rolls", name: "Sushi fur 1 Person", description: "2 Nigiri Lachs oder Garnelen, 8 Inside Out Lachs, Surimi oder Avocado, 4 Maki Lachs oder Avocado und 4 Maki Gurke oder Avocado.", price: 15.9 },

  { id: "n84", category: "nudeln", name: "Bun Cha Nuong Ha Noi", description: "Reisnudeln mit gegrilltem Schweinefleisch, Salat und Krautern, dazu hausgemachte Sauce.", price: 14.9 },

  { id: "d100", category: "dessert", name: "100. Chuoi Chien", description: "Gebackene Bananenballchen, verfeinert mit Honig, dazu Vanilleeis.", price: 6 },
  { id: "d101", category: "dessert", name: "101. Banh Dua Chien", description: "Gebackene Kokosballchen, verfeinert mit Honig.", price: 6 },
  { id: "d102", category: "dessert", name: "102. Banh Bao Hap Nhan Hat Sen", description: "Gedampfte Hefeteigklosse mit susser Lotuspaste in Kokosmilchsosse.", price: 6 },
  { id: "d103", category: "dessert", name: "103. Mochi-Eis Platte", description: "Klebreisballchen mit Eiscremefullung, garniert mit Fruchten.", price: 7.5 },

  { id: "g_b01", category: "getraenke", name: "Helles 0,5L", description: "Mildes helles Bier mit Malz, Hopfen und feiner Kohlensaure.", price: 4.5 },
  { id: "g_b02", category: "getraenke", name: "Weissbier 0,5L", description: "Weizenbier mit weicher Hefe, Malz und fruchtiger Note.", price: 4.8 },
  { id: "g_b03", category: "getraenke", name: "Dunkles Weissbier 0,5L", description: "Dunkles Weizenbier mit Rostmalz, Hefe und sanfter Susse.", price: 4.8 },
  { id: "g_b04", category: "getraenke", name: "Leichtes Weissbier 0,5L", description: "Leichtes Weizenbier mit Hefe, Malz und frischer Perlage.", price: 4.8 },
  { id: "g_b05", category: "getraenke", name: "Alkoholfrei Helles 0,5L", description: "Alkoholfreies helles Bier mit Malz, Hopfen und frischem Finish.", price: 4.5 },
  { id: "g_b06", category: "getraenke", name: "Pils 0,33L", description: "Herbes Pils mit Hopfen, Malz und klarer Bitterkeit.", price: 3.9 },
  { id: "g_b07", category: "getraenke", name: "Singha Beer 0,33L", description: "Thailandisches Lagerbier mit leichter Malznote.", price: 3.9 },
  { id: "g_b08", category: "getraenke", name: "Radler 0,5L", description: "Helles Bier gemischt mit Zitronenlimonade.", price: 4.5 },
  { id: "g_b09", category: "getraenke", name: "Russ'n 0,5L", description: "Weissbier gemischt mit Zitronenlimonade.", price: 4.8 },
  { id: "g_b10", category: "getraenke", name: "Colaweizen 0,5L", description: "Weissbier gemischt mit Coca-Cola.", price: 4.8 },

  { id: "g_t01", category: "getraenke", name: "Eilles Gruntee Asia Superior Blatt", description: "Unfermentierter Tee aus China.", price: 4 },
  { id: "g_t02", category: "getraenke", name: "Eilles Bio Gruntee Jasmin Blatt", description: "Gruner Tee mit Jasminbluten.", price: 4.5 },
  { id: "g_t03", category: "getraenke", name: "Eilles Kamillenbluten", description: "Milder Tee mit honigartigem Geschmack.", price: 4 },
  { id: "g_t04", category: "getraenke", name: "Frischer Ingwertee", description: "Frischer Ingwer, heisses Wasser und auf Wunsch Honig.", price: 4.5 },
  { id: "g_t05", category: "getraenke", name: "Frischer Zitronengrastee", description: "Frisches Zitronengras, heisses Wasser und feiner Zitrusduft.", price: 4.5 },
  { id: "g_t06", category: "getraenke", name: "Frischer Pfefferminztee", description: "Frische Minze, heisses Wasser und klare Krauternote.", price: 4.5 },

  { id: "g_s01", category: "getraenke", name: "Coca-Cola 0,33L", description: "Klassische Cola mit Kohlensaure und Koffein.", price: 3.5 },
  { id: "g_s02", category: "getraenke", name: "Cola Zero 0,33L", description: "Zuckerfreie Cola mit Kohlensaure und Koffein.", price: 3.5 },
  { id: "g_s03", category: "getraenke", name: "Fanta 0,33L", description: "Orangenlimonade mit Kohlensaure.", price: 3.5 },
  { id: "g_s04", category: "getraenke", name: "Sprite 0,33L", description: "Zitronen-Limetten-Limonade mit Kohlensaure.", price: 3.5 },
  { id: "g_s05", category: "getraenke", name: "Mezzo Mix 0,33L", description: "Cola-Orangen-Mix mit Kohlensaure.", price: 3.5 },
  { id: "g_w01", category: "getraenke", name: "Flaschenwasser ohne Kohlensaure 0,25L", description: "Stilles Mineralwasser in der kleinen Flasche.", price: 2.9 },
  { id: "g_w02", category: "getraenke", name: "Flaschenwasser ohne Kohlensaure 0,75L", description: "Stilles Mineralwasser fur den Tisch.", price: 6 },
  { id: "g_w03", category: "getraenke", name: "Flaschenwasser wenig Kohlensaure 0,25L", description: "Mineralwasser mit leichter Kohlensaure.", price: 2.9 },
  { id: "g_w04", category: "getraenke", name: "Flaschenwasser wenig Kohlensaure 0,75L", description: "Mineralwasser mit leichter Kohlensaure fur den Tisch.", price: 6 },
  { id: "g_w05", category: "getraenke", name: "Tafelwasser", description: "Frisches Tafelwasser, still oder spritzig.", price: 2.5 },
  { id: "g_sw01", category: "getraenke", name: "Ginger Ale 0,2L", description: "Ingwerlimonade mit feiner Susse.", price: 2.9 },
  { id: "g_sw02", category: "getraenke", name: "Wild Berry 0,2L", description: "Beerenlimonade mit Kohlensaure.", price: 2.9 },
  { id: "g_sw03", category: "getraenke", name: "Tonic Water 0,2L", description: "Herb-bitteres Tonic mit Kohlensaure.", price: 2.9 },

  { id: "g_sa01", category: "getraenke", name: "Saft 0,2L", description: "Apfel, Litschi, Mango, Maracuja, Guave, Rhabarber, Johannisbeere, Orange oder Ananas.", price: 3.6 },
  { id: "g_sa02", category: "getraenke", name: "Saft 0,33L", description: "Apfel, Litschi, Mango, Maracuja, Guave, Rhabarber, Johannisbeere, Orange oder Ananas.", price: 4.5 },
  { id: "g_sa03", category: "getraenke", name: "Schorle 0,2L", description: "Fruchtsaft nach Wahl mit Mineralwasser.", price: 3.5 },
  { id: "g_sa04", category: "getraenke", name: "Schorle 0,33L", description: "Fruchtsaft nach Wahl mit Mineralwasser.", price: 4.2 },
  { id: "g_detox", category: "getraenke", name: "Unser Detox-Wasser 0,5L", description: "Mit frischem Obst, Saisongemuse und aromatischen Krautern.", price: 5.9 },

  { id: "g_e01", category: "getraenke", name: "Nuoc Chanh Day", description: "Frische Limette, brauner Zucker und Soda.", price: 5.9 },
  { id: "g_e02", category: "getraenke", name: "Nuoc Chanh Sa Da", description: "Frische Limette, brauner Zucker, Zitronengras und Soda.", price: 5.9 },
  { id: "g_e03", category: "getraenke", name: "Nuoc Chanh Cam Da", description: "Frische Limette, Orange und brauner Zucker.", price: 5.9 },
  { id: "g_e04", category: "getraenke", name: "White Lady", description: "Litschi, Ananas, Holundersirup und Kokosmilch.", price: 6.9 },
  { id: "g_e05", category: "getraenke", name: "Summer Breeze", description: "Ananas, Minze und Kokosmilch.", price: 6.9 },
  { id: "g_e06", category: "getraenke", name: "Vitamin Punch", description: "Orange, Ananas und Mango.", price: 6.9 },
  { id: "g_e07", category: "getraenke", name: "Summer Sakura", description: "Limette, Litschi und Ginger Ale.", price: 6.9 },
  { id: "g_e08", category: "getraenke", name: "Touch of Raspberry", description: "Himbeeren, Limette, Minze und Sprite.", price: 6.9 },
  { id: "g_e09", category: "getraenke", name: "Himbeer Eistee", description: "Himbeeren, Limette und gruner Tee.", price: 6.9 },
  { id: "g_e10", category: "getraenke", name: "Ginger Lemonade", description: "Ingwer, Limette, Orange, Koriander und Ginger Beer.", price: 6.9 },

  { id: "g_a01", category: "getraenke", name: "Aperol Spritz", description: "Aperol, Prosecco, Orange und Soda.", price: 6.5 },
  { id: "g_a02", category: "getraenke", name: "Aperol Litschi Spritz", description: "Aperol, Prosecco, Litschisaft und Soda.", price: 6.5 },
  { id: "g_a03", category: "getraenke", name: "Hugo", description: "Holundersirup, Prosecco, Limette, Minze und Soda.", price: 6.5 },
  { id: "g_a04", category: "getraenke", name: "Campari Soda oder Orange", description: "Campari mit Sodawasser oder Orangensaft.", price: 6.5 },
  { id: "g_a05", category: "getraenke", name: "Lillet Wild Berry", description: "Lillet Blanc, Prosecco, frische Beeren und Wild Berry.", price: 7 },
  { id: "g_l01", category: "getraenke", name: "Gin Tonic", description: "Dry Gin, Tonic Water und Gurke.", price: 8 },
  { id: "g_l02", category: "getraenke", name: "Vodka Redbull", description: "Vodka, Redbull und Limette.", price: 8 },
  { id: "g_l03", category: "getraenke", name: "Whisky Cola", description: "Whisky und Coca-Cola.", price: 8 },
  { id: "g_l04", category: "getraenke", name: "Cuba Libre", description: "Rum und Coca-Cola.", price: 8 },
  { id: "g_l05", category: "getraenke", name: "Jameson Ginger", description: "Jameson Whisky, Limette, Ginger Ale und Minze.", price: 8 },

  { id: "g_c01", category: "getraenke", name: "Mai Tai", description: "Rum, Cointreau, Mandelsirup, Limetten, Ananas- und Orangensaft.", price: 8.5 },
  { id: "g_c02", category: "getraenke", name: "Mojito", description: "Rum, brauner Zucker, Limette, Minze, Ginger Ale und Soda.", price: 8.5 },
  { id: "g_c03", category: "getraenke", name: "Litschi Mojito", description: "Rum, Limette, Litschisaft, Minze und Soda.", price: 8.5 },
  { id: "g_c04", category: "getraenke", name: "Pina Colada", description: "Weisser Rum, Kokossirup, Kondensmilch, Ananas- und Orangensaft.", price: 8.5 },
  { id: "g_c05", category: "getraenke", name: "Tequila Sunrise", description: "Tequila, Grenadine, Limettensaft und Orangensaft.", price: 8.5 },
  { id: "g_c06", category: "getraenke", name: "Blue Ocean", description: "Dry Gin, Blue Curacao, Kokossirup, Limette und Ananassaft.", price: 8.5 },
  { id: "g_c07", category: "getraenke", name: "No Money No Honey", description: "Brauner Rum, Apricot Brandy, Kokossirup, Ananas- und Maracujasaft, Muskatnuss.", price: 8.5 },
  { id: "g_c08", category: "getraenke", name: "Gin Bee", description: "Dry Gin, Honig, Minze und Soda.", price: 8.5 },

  { id: "g_wi01", category: "getraenke", name: "Weinschorle 0,1L", description: "Wein mit spritzigem Mineralwasser.", price: 3.9 },
  { id: "g_wi02", category: "getraenke", name: "Weinschorle 0,2L", description: "Wein mit spritzigem Mineralwasser.", price: 5.9 },
  { id: "g_wi03", category: "getraenke", name: "Chiaretto Classico DOC Corte Olivi 0,2L", description: "Rosewein, fruchtig und leicht gekuhlt serviert.", price: 6.9 },
  { id: "g_wi04", category: "getraenke", name: "Chiaretto Classico DOC Corte Olivi 0,75L", description: "Rosewein, fruchtig und leicht gekuhlt serviert.", price: 24 },
  { id: "g_wi05", category: "getraenke", name: "Prosecco Frizzante DOC Bertoldi 0,1L", description: "Fein perlender Prosecco mit frischem Auftakt.", price: 3.9 },
  { id: "g_wi06", category: "getraenke", name: "Merlot-Primitivo IGT Tarantino 0,2L", description: "Rotwein-Cuvee mit weicher Frucht und rundem Korper.", price: 6.9 },
  { id: "g_wi07", category: "getraenke", name: "Merlot-Primitivo IGT Tarantino 0,75L", description: "Rotwein-Cuvee mit weicher Frucht und rundem Korper.", price: 24 },
  { id: "g_wi08", category: "getraenke", name: "Tres IGP Antico Ceppo 0,2L", description: "Italienischer Rotwein mit dunkler Frucht und milder Wurze.", price: 6.5 },
  { id: "g_wi09", category: "getraenke", name: "Tres IGP Antico Ceppo 0,75L", description: "Italienischer Rotwein mit dunkler Frucht und milder Wurze.", price: 22 },
  { id: "g_wi10", category: "getraenke", name: "Primitivo di Manduria DOC 0,2L", description: "Kraftiger Rotwein mit reifer Frucht und samtigem Finish.", price: 6.9 },
  { id: "g_wi11", category: "getraenke", name: "Primitivo di Manduria DOC 0,75L", description: "Kraftiger Rotwein mit reifer Frucht und samtigem Finish.", price: 24 },
  { id: "g_wi12", category: "getraenke", name: "Montepulciano DOC 0,2L", description: "Vollmundiger Rotwein mit Kirschnote und weichen Tanninen.", price: 7.5 },
  { id: "g_wi13", category: "getraenke", name: "Montepulciano DOC 0,75L", description: "Vollmundiger Rotwein mit Kirschnote und weichen Tanninen.", price: 26 },
];
